### ISSUE TITLE
Large number of skipped contigs

### ISSUE THREAD

**Issue by balazshorvathreal** [ChengPENG-wolf/ViraLM#1]
First of all, let me congratulate you on this very promising and, according to our own benchmarks, cutting edge application! 
It indeed performs an order of magnitude better than e.g. Virsorter2, DeepMicroclass, DeepVirFinder etc., but we find the following interesting observation: from a real metagenomic sample of ~22000 contigs, we get no any information about 89% of the contigs in the output, what could be the reason for this? ? Do these contigs belong to the non-viral bin?  

CLI: python viralm.py --input 408_Ae_vex-combined.fa --out 408_Ae_vex --len 300 (CPU mode, 192 AMD Epyc cores)

![image](https://github.com/ChengPENG-wolf/ViraLM/assets/82114449/20accab1-0178-4a54-aaa5-88ee84fc15ba)

Many thanks: Balázs

**Comment by ChengPENG-wolf** [comment]
Thank you for your kind words on ViraLM. We are delighted to hear that our tool is performing well on your own benchmarks. Since ViraLM was not trained on contigs shorter than 500 bp and such short contigs may lack sufficient information for prediction we set the minimum length of ViraLM to be 500 bp to ensure optimal performance. As a result, although you specified the –-len to be 300, ViraLM will still skip the contigs shorter than 500 bp. Regarding your feedback, I will make some efforts to provide a better user experience.

**Comment by ChengPENG-wolf** [comment]
Hi, I have modified the` viralm.py` file so that the `--len` option will work with a value smaller than 500. For example, if you set `--len 0`, then ViraLM will not skip any input contigs. However, we still recommend setting  `--len` to a value larger than 500 for optimal performance.

**Comment by balazshorvathreal** [comment]
Wow, that was fast! Thank you, I will definitely try it, e.g. it will be particularly useful in the search for Lassavirus-like short Z proteins - even with the limitations of short length.
